### ISSUE TITLE
Feature request: scrolling in UI

### ISSUE THREAD

**Issue by PFGimenez** [chaosforgeorg/jh-mods#1]
A feature request for modding: scrolling in UI.

Currently, a few UI have scrolling, like the load game UI:
![image](https://github.com/chaosforgeorg/jh-mods/assets/11853513/bafd5a14-f491-4c31-9a34-6310f8ca82b6)
In this example, the player can easily check all his saves.

The challenge selection UI does not have scrolling: if there are too many challenges, the user can still select the challenge they want but the left part of the UI won’t scroll down.
![image](https://github.com/chaosforgeorg/jh-mods/assets/11853513/48f95918-6454-4dfa-8a4c-59e3e7116621)

Here is a list of some UI that could benefit from scrolling for modding purpose:
- challenge selection
- trial selection
- help menu (for HellpediaCE notably)
- list of traits

cpiod

**Comment by epyon** [comment]
Implemented fully in 1.7 RC3
