### ISSUE TITLE
Bug: text.lua in mods is not loaded

### ISSUE THREAD

**Issue by PFGimenez** [chaosforgeorg/jh-mods#2]
`text.lua` is supposed to be loaded when placed in the mod directory (next to main.lua), but it is not.
I experimented with the following `text.lua`:

```
nova.log("Hello from text.lua")
strings.ui.game.main_menu.help="HellpediaCE"
strings.ui.game.ingame_menu.help=" HellpediaCE "
```

Neither the log nor the change of strings occur.

cpiod

**Comment by epyon** [comment]
Should be fixed in 1.7 RC3
