### ISSUE TITLE
Feature request: disable achievements on demand

### ISSUE THREAD

**Issue by PFGimenez** [chaosforgeorg/jh-mods#3]
Afaik, playing with mods still affect scoretables, player data and achievements update.

Since automatically assessing whether a mod is cheating or not is tricky, the game could expose a function to disable these updates, so each modder can chose whether their mod should be considered cheating or not.

**Comment by PFGimenez** [comment]
In fact, it would be best to ask the mod, at the end of a run, whether the achievements/medals should be disabled for this run.
For example:
- medic class mod would answer "yes, disable achievement" if the medic class is used, "no" otherwise
- assembly trait mod would answer "yes, disable achievement" if the assembly trait has been purchased by the user
- etc.

**Comment by epyon** [comment]
ui:allow_achievements(bool) and ui:allow_statistics(bool) added to 1.8 RC2
