### ISSUE TITLE
Feature request: ignore .git when uploading 

### ISSUE THREAD

**Issue by PFGimenez** [chaosforgeorg/jh-mods#4]
My HellpediaCE mods directory size is 75KB (for the sources) + 1.4MB for the .git directory. I guess I’m not the only one to use a repository to manage my code, so I propose to ignore the `.git` folder while uploading a mod. Maybe it could help stay within Steam quotas (not sure if that’s a concern).

cpiod

**Comment by epyon** [comment]
The Steam API for mod uploading expects a path to a folder. There's nothing else you can control there, no per-file picking, no wildcards :(. Maybe keep the mods in git in a subfolder always? (I don't remember if .git exists only in root folder)
